apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal-mysql
  name: drupal-mysql-service
spec:
  type: ClusterIP
  ports:
  - name: drupal-mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: drupal-mysql